services:
    mysql:
        image: mysql:5.7
        restart: always
        container_name: mysql
        tty: true
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'usuario'
            MYSQL_PASSWORD: 'senha'
            MYSQL_ROOT_PASSWORD: 'senharoot'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql-vol:/var/lib/mysql
        networks:
            - desafio
        healthcheck:
            #test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 15s
            timeout: 10s
            retries: 3

    node:
        container_name: node
        tty: true
        build:
            context: ./node
        ports:
            - "3000:3000"
        networks:
            - desafio
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:3000"]
            interval: 5s
            timeout: 10s
            retries: 3
        #volumes:
        #    - ./node:/usr/src/app
        depends_on:
            mysql:
              condition: service_healthy

    nginx:
        container_name: nginx
        tty: true
        restart: always
        build:
            context: ./nginx
        ports:
            - '8080:80'
        networks:
            - desafio    
        depends_on:
            node:
                condition: service_healthy

networks:
    desafio:
        driver: bridge

volumes:
    mysql-vol:        
      